default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mini_series_tester_development

test:
  <<: *default
  database: mini_series_tester_test

production:
  <<: *default
  database: mini_series_tester_production
