# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25be958f4d2dcc5125ffb2301b1278465e3d70fbca91b09c3d60d451b752c5b953859f4ee142890a36ba5eaf94a526e56f2387e87f68de9aa603a68f7679269e

test:
  secret_key_base: 57d2498a11dab5604aff9911195c0882b87c8c6043e7e9a92dc303258f61a89853daf6c400e9c299426c1902af6bf82e9af17c9e7c530ca74a397bd92109bb17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
